-- Create a table to track which users have blocked which other users.
-- When a user blocks someone, they should no longer see any of that person's moments.

create table if not exists public.blocked_users (
  id bigint generated by default as identity primary key,
  blocker_id uuid not null references public.profiles (id) on delete cascade,
  blocked_user_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint blocked_users_blocker_blocked_unique unique (blocker_id, blocked_user_id),
  constraint blocked_users_no_self_block check (blocker_id <> blocked_user_id)
);

comment on table public.blocked_users is
  'Tracks one-way user blocks. When a user blocks someone, they should no longer see any of that user''s posts.';

comment on column public.blocked_users.blocker_id is
  'The user who is blocking another user.';

comment on column public.blocked_users.blocked_user_id is
  'The user who has been blocked and whose moments should not appear in the blocker''s feed.';

